namespace AuthService.Entities;

/// <summary>
/// Abstract base entity inherited by all domain entities.
/// Uses Snowflake (IdGen) long ID for distributed, time-ordered, unique identifiers.
/// </summary>
public abstract class BaseEntity
{
    /// <summary>Snowflake ID generated by IdGen (64-bit long).</summary>
    public long Id { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    public long? CreatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public long? UpdatedBy { get; set; }

    public bool IsDeleted { get; set; } = false;
}
