services:

  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "5086:8080"

  authservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__AuthDb=Server=sqlserver,1433;Database=${MSSQL_DB:-AuthDb};User Id=sa;Password=${MSSQL_SA_PASSWORD:-Password123!};TrustServerCertificate=True;MultipleActiveResultSets=true;
      - Jwt__Key=${JWT_SECRET:-YOUR_SUPER_SECRET_KEY_CHANGE_IN_PRODUCTION_MIN_32_CHARS}
      - Jwt__Issuer=${JWT_ISSUER:-FlowersAuth}
      - Jwt__Audience=${JWT_AUDIENCE:-FlowersApp}
    ports:
      - "5022:8080"

  catalogservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__CatalogServiceDb=Server=sqlserver,1433;Database=CatalogServiceDb;User Id=sa;Password=${MSSQL_SA_PASSWORD:-Password123!};TrustServerCertificate=True;MultipleActiveResultSets=true;
      - Jwt__Key=${JWT_SECRET:-YOUR_SUPER_SECRET_KEY_CHANGE_IN_PRODUCTION_MIN_32_CHARS}
      - Jwt__Issuer=${JWT_ISSUER:-FlowersAuth}
      - Jwt__Audience=${JWT_AUDIENCE:-FlowersApp}
    ports:
      - "5129:8080"

  cartservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "5292:8080"

  orderservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "5109:8080"

  paymentservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "5260:8080"

  addressservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "5272:8080"

  sqlserver:
    ports:
      - "1433:1433"
